version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: groupone
      POSTGRES_PASSWORD: groupOneRocks

  # AI Service (FastAPI)
  ai-service:
    build: ./code/ai-service
    ports:
      - "9080:9080"
    volumes:
      - ./code/ai-service:/app
    environment:
      - FLASK_ENV=development

  # Backend (Spring Boot)
  course-builder-chatbot-ms:
    build:
      context: ./code/backend/course-builder-chatbot-ms
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ai-service
      - db

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./code/frontend  # Updated context path after moving files
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Exposing port 80 inside container to port 3000 outside
    volumes:
      - ./code/frontend:/app
    depends_on:
      - course-builder-chatbot-ms
    environment:
      - NODE_ENV=production

volumes:
  postgres_data:
  ai-service-data:
  course-builder-chatbot-ms-data:
